// lessonId → 図解URL マップ
// 図解を追加するときはここに1行追加するだけ
export const LESSON_DIAGRAM_LINKS: Record<string, string> = {
  "ts-01-variable-types": "/diagrams/lessons/ts-01-variable-types.html",
  "ts-02-function-types": "/diagrams/lessons/ts-02-function-types.html",
  "ts-03-object-types": "/diagrams/lessons/ts-03-object-types.html",
  "ts-04-type-alias": "/diagrams/lessons/ts-04-type-alias.html",
  "ts-05-interface": "/diagrams/lessons/ts-05-interface.html",
  "ts-06-union-literal": "/diagrams/lessons/ts-06-union-literal.html",
  "ts-07-type-guards": "/diagrams/lessons/ts-07-type-guards.html",
  "ts-08-array-types": "/diagrams/lessons/ts-08-array-types.html",
  "ts-09-optional": "/diagrams/lessons/ts-09-optional.html",
  "ts-10-crud-basics": "/diagrams/lessons/ts-10-crud-basics.html",
  "ts-11-generics-basics": "/diagrams/lessons/ts-11-generics-basics.html",
  "ts-12-promise": "/diagrams/lessons/ts-12-promise.html",
  "ts-13-async-await": "/diagrams/lessons/ts-13-async-await.html",
  "ts-14-error-handling": "/diagrams/lessons/ts-14-error-handling.html",
  "ts-15-api-fetch": "/diagrams/lessons/ts-15-api-fetch.html",
  "ts-16-component-props": "/diagrams/lessons/ts-16-component-props.html",
  "ts-17-usestate": "/diagrams/lessons/ts-17-usestate.html",
  "ts-18-form-input": "/diagrams/lessons/ts-18-form-input.html",
  "ts-19-discriminated-union": "/diagrams/lessons/ts-19-discriminated-union.html",
  "ts-20-exhaustive-check": "/diagrams/lessons/ts-20-exhaustive-check.html",
  "ts-21-utility-types": "/diagrams/lessons/ts-21-utility-types.html",
  "ts-22-record-type": "/diagrams/lessons/ts-22-record-type.html",
  "ts-23-keyof": "/diagrams/lessons/ts-23-keyof.html",
  "ts-24-mapped-types": "/diagrams/lessons/ts-24-mapped-types.html",
  "ts-25-useeffect-cleanup": "/diagrams/lessons/ts-25-useeffect-cleanup.html",
  "ts-26-usecontext": "/diagrams/lessons/ts-26-usecontext.html",
  "ts-27-usereducer": "/diagrams/lessons/ts-27-usereducer.html",
  "ts-28-custom-hook-pattern": "/diagrams/lessons/ts-28-custom-hook-pattern.html",
};
